const express = require('express')
const pool = require('../utilities').pool
const validation = require('../utilities').validation
const path = require('path');
let isStringProvided = validation.isStringProvided
let isValueProvided = validation.isValueProvided

const router = express.Router()


/**
 * @api {put} /verification Verify an account
 * @apiName getVerification
 * @apiGroup Verification
 * 
 * @apiParam {String} code The autogenerated code that is sent in the verification link
 * 
 * 
 * @apiSuccess {boolean} success true when the user has been verified
 * 
 * @apiError (400: Missing Parameters) {String} message "Missing required information"
 * 
 * @apiError (400: SQL Error) {String} message the reported SQL error details
 */ 
router.get('/:str',  (request, response) => {
    const {str} = request.params
    let insert = `SELECT * From Members WHERE Verification = $1`
    let values = [str]
    pool.query(insert, values)
        .then(result => {
            let insert = `UPDATE Members SET Verified = $1 WHERE Verification = $2`
            let values = [true, str]
            pool.query(insert, values)
            .then(result => {
                
                
                response.sendFile(path.join(__dirname, '/index.html'))
                
                

            }).catch(err => {
                
                response.send({
                    message: "SQL Error",
                    rows: {},
                    error: err
                })

        })

        }).catch(err => {
            
            response.send({
                message: "SQL Error",
                rows: {},
                error: err
            })

        })
})

module.exports = router